# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c948453a6123e9030c2082cf091e9187142844f8a6c64cd2fa563e4a1720fcb6badec1caaa5534cb7f6c75155e217708dc2103c999f7a8bf1cdb1951c37c4e09

test:
  secret_key_base: 1c6ec830502ef211dd795b6a0f5f9b4a3876f3c5e3959c485315511e3db2769ac2fe73e35d2700789cbc6d2acdbc0a4f93228f73c53ffda6e0015742e5d40c55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
